---
- name: update cache
  apt:
    update_cache: yes

- name: Install nginx
  apt:
    name: nginx
    state: latest
  notify: 
    - Start_enable_nginx

- name: Configure index.html
  template: 
    src: index.html.j2 
    dest: /var/www/html/index.html 
    owner: root 
    group: root 
    mode: 0644 
  become: True 
  notify: restart_nginx