---

- hosts: localhost
  gather_facts: False
  
  vars:

    region: us-east-1
    image: ami-0557a15b87f6559cf # ubuntu 20.04 LTS
    id: "ec2-ansible-ngix"
    sec_group: "${{ id }}-sec"
    profile_key: default
  
  tasks:

    - name: create security group

      amazon.aws.ec2_security_group:
        
        name: "{{vars.sec_group}}"
        description: "Security group for instance ec2 {{var.id}}"
        region: "{{vars.region}}"
        
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            group_name: other-group
            # description to use if example-other needs to be created
            group_desc: other create security group
      
      register: sec_group_id

    - name: provision an EC2 instance with ansible

      amazon.aws.ec2:

        aws_profile: default
        name: "{{id}}"
        key_name: "ec2-vagrant-ssh-key"
        vpc_subnet_id: default
        instance_type: t2.micro
        security_group: "{{sec_group_id.group_id}}"
        network:
          assing_public_ip: true
        image_id: "{{vars.image}}"
        tags:
          Enviroment: Testing
      register: result

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      loop: "{{ result.instances }}"  
