---
- name: Create Free Tier EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  
  vars:
    region: us-east-1
    name: "ec2-ansible-ngix"
    sec_group: "${{ name }}-sec"
    instance_type: t2.micro
    keypair: Teste-Ansible
    image:
      id: ami-0557a15b87f6559cf	
  
    
  tasks:
  
    - name: "create security group" 
      ec2_group:
        name: "{{name}}"
        description: "Security group for instance ec2 {{name}}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on ssh port

          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all http  port
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            group_desc: other create security group
      register: sec_group_id

    - name: "provision an EC2 instance"
      ec2_instance:
        key_name: "{{keypair}}"
        name: "{{name}}"
        image: "{{image}}"
        instance_type: "{{instance_type}}"
        region: "{{ region }}"
        security_group: "{{sec_group_id.group_id}}"
        network:
          assing_public_ip: true
        tags:
          Environment: Testing
        wait: true
      register: instance_ec2

    - name: Print all instances
      debug:
        var: instance_ec2
